var icons = {
    "http://webinos.org/api/sensors/temperature": "temperature-icon.png",
    "http://webinos.org/api/sensors/humidity": "humidity-icon.png",
    "http://webinos.org/api/sensors/light": "light-icon.png",
    "http://webinos.org/api/sensors/voltage": "voltage-icon.png",
    "http://webinos.org/api/sensors/electricity":"electricity-icon.png",
    "http://webinos.org/api/actuators/switch": "switch-icon.png",
    "http://webinos.org/api/sensors/proximity": "proximity-icon.png",
    "http://webinos.org/api/actuators/linearmotor": "switch-icon.png",
    "http://webinos.org/api/sensors/heartratemonitor": "heartratemonitor-icon.png",
    "http://webinos.org/api/sensors/rpm": "obd-icon.png",
    "http://webinos.org/api/sensors/vss": "obd-icon.png",
    "http://webinos.org/api/sensors/load_pct": "obd-icon.png",
    "http://webinos.org/api/sensors/throttlepos": "obd-icon.png",
    "http://webinos.org/api/sensors/frp": "obd-icon.png",
    "http://webinos.org/api/sensors/temp": "obd-icon.png",
    "http://webinos.org/api/sensors/iat": "obd-icon.png",
    "http://webinos.org/api/sensors/pidsupp0": "obd-icon.png",
    "http://webinos.org/api/sensors/dtc_cnt": "obd-icon.png",
    "http://webinos.org/api/sensors/dtcfrzf": "obd-icon.png",
    "http://webinos.org/api/sensors/fuelsys": "obd-icon.png",
    "http://webinos.org/api/sensors/shrtft13": "obd-icon.png",
    "http://webinos.org/api/sensors/longft13": "obd-icon.png",
    "http://webinos.org/api/sensors/shrtft24": "obd-icon.png",
    "http://webinos.org/api/sensors/longft24": "obd-icon.png",
    "http://webinos.org/api/sensors/map": "obd-icon.png",
    "http://webinos.org/api/sensors/sparkadv": "obd-icon.png",
    "http://webinos.org/api/sensors/maf": "obd-icon.png",
    "http://www.w3.org/ns/api-perms/geolocation": "geolocation-icon.png"
};